version: "3"
services:
  db:
    image: library/mysql:5.7
    container_name: dev_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./mysql:/var/lib/mysql
