spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_agile?useSSL=false&serverTimezone=UTC
    username: <username>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
