INSERT INTO account(email,username,password) VALUES('test@test.com','testuser','testpass');

INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
INSERT INTO post(account_id,category,title,content,price) VALUES(1,'category','test title','test content',35000);
